id: unitsarefailing_what_is_flakiness
hints:
- Focus on the types of flaky tests in the link
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Which test is failing for you?"
        delay: 1300
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
            - "one_comment3"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Yep, that's the same one that's failing for me"
              delay: 1500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Umm, strange. I'm seeing the failure in a different test. Are you sure you got the right one? Let's try again"
              delay: 1400
