id: unitsarefailing_what_is_flakiness
hints:
- Focus on the types of flaky tests in the link
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Which test is failing for you?"
        delay: 1300
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: keen
          messages:
          - text: "Oh wow, I have a different one failing for me. Looks like we have some flaky tests here"
            delay: 1500
      - actionId: finish_step
