id: unitsarefailing_identify_file
hints:
- Use <command> to run a specific test
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Ok, great. Now that we've found the failing test, let's try running it individually. Is it working?"
        delay: 1300
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
            - "yes"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Interesting. So it's working in isolation, yet failing when run together with the others. Well, looks like we have a flaky test on our hands... If you're interested, [this is my favorite read](https://docs.gitlab.com/ee/development/testing_guide/flaky_tests.html) on flaky tests""
              delay: 1500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Umm, it's working for me. Are you sure you have the right one? Please try again and let me know if it's working"
              delay: 1400
