id: unitsarefailing_identify_file
hints:
- Use <command> to run a specific test
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Can you try running each of the tests individually? Are they working?"
        delay: 1300
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
            - "yes"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Super weird (and kind of cool). [this is my favorite read](https://docs.gitlab.com/ee/development/testing_guide/flaky_tests.html) on flaky tests, maybe we can find some hints there."
              delay: 1500
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Umm, they're working for me when I run them individually. Are you sure you're doing everything right?"
              delay: 1400
